#!/usr/bin/env bash

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service
sudo service nginx start

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
echo "server {
    listen 80;
    server_name 35.153.66.223;
    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirection

# Enable the configuration by creating a symbolic link to the sites-enabled directory
sudo ln -s /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
