#!/usr/bin/env bash
# checks if file exits and print whether it does or not
# also checks if the files is empty and prints whether it is or not

if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
